default:
  # Official docker image.
  image: docker:latest  
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]

stages:
  - build
  - release

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker logout

pushrm:
  stage: release
  image:
    name: chko/docker-pushrm
    entrypoint: ["/bin/sh", "-c", "/docker-pushrm"]
  variables:
    DOCKER_USER: $CI_REGISTRY_USER
    DOCKER_PASS: $CI_REGISTRY_PASSWORD
    PUSHRM_SHORT: Proxmox QDevice in a Container
    PUSHRM_TARGET: docker.io/$CI_REGISTRY_USER/proxmox-qdevice
    PUSHRM_DEBUG: 1
    PUSHRM_FILE: $CI_PROJECT_DIR/README.md
  script: "/bin/true"
