default:
  # Official docker image.
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]

stages:
  - build
  - release

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker logout

#release:
#  stage: release
#  script:
#    - docker run --rm -t -v $(pwd):/myvol -e DOCKER_USER='$CI_REGISTRY_USER' -e DOCKER_PASS='$CI_REGISTRY_PASSWORD' -e PUSHRM_PROVIDER=dockerhub -e PUSHRM_FILE=/myvol/README.md -e PUSHRM_SHORT='Proxmox QDevice in a Container' -e PUSHRM_TARGET=docker.io/$CI_REGISTRY_USER/proxmox-qdevice -e PUSHRM_DEBUG=1 chko/docker-pushrm
