services:
  qnetd:
    container_name: proxmox-qdevice
    image: bcleonard/proxmox-qdevice:v2.0
    build: .
    ports:
      - "22:22"
      - "5403:5403"
    environment:
    volumes:
      - /run/sshd
      - <MY LOCAL STORAGE>:/etc/corosync
    restart: unless-stopped
    hostname: <MY FQDN>
    networks: 
      vlan:
        ipv4_address: <MY IP ADDRESS>

networks:
 vlan:
    driver: macvlan
    driver_opts:
      parent: <MY ETHERNET DEVICE>
    ipam:
       driver: default
       config:
        - subnet: "<MY SUBNET/MY RANGE"
          ip_range: "<MY IP ADDRESS (same as above)>/32"
          gateway: "<MY GATEWAY>"
